name-template: "$NEXT_MINOR_VERSION"
tag-template: "$NEXT_MINOR_VERSION"
categories:
  - title: "⭐ New Features"
    labels:
      - "experimental"
      - "feature request"
  - title: "🔧 Optimizations"
    labels:
      - "optimization"
      - "refactor"
  - title: "📄 Documentation"
    labels:
      - "documentation"
  - title: "❌ Removed"
    labels:
      - "deprecated"
  - title: "🐞 Bug Fixes"
    labels:
      - "bug"
      - "critical bug"
  - title: "📘 Dependencies"
    label: "dependencies"
exclude-labels:
  - "website"
no-changes-template: "*No changes*"
change-template: "- $TITLE #$NUMBER (@$AUTHOR)"
template: |
  # 🌈 Changes

  $CHANGES
