blank_issues_enabled: false
contact_links:
  - name: Feature Requests
    url: https://github.com/Katsute/MyAnimeList-Java-API/discussions/categories/feature-requests
    about: New feature requests must be posted here first before they may become an issue
  - name: Discussions
    url: https://github.com/Katsute/MyAnimeList-Java-API/discussions
    about: Check here before posting an issue
  - name: Official MyAnimeList API Club
    url: https://myanimelist.net/clubs.php?cid=13727
    about: We do not maintain the MyAnimeList API, issues regarding the API itself should be posted in their official club