blank_issues_enabled: false
contact_links:
  - name: Reporting an issue on GitHub app.
    about: The GitHub mobile app doesn't yet support issue forms, you must open in a browser instead
    url: https://github.com/Katsute/Mal4J/issues
  - name: Known Issues
    about: Certain issues are caused by the MyAnimeList API and not this library, check here for a list of those issues
    url: https://github.com/Katsute/Mal4J/discussions/136
  - name: Documentation
    about: Check the documentation before posting an issue
    url: https://mal4j.katsute.dev
  - name: FAQ
    about: Check frequently asked questions before posting an issue
    url: https://github.com/Katsute/Mal4J/blob/main/faq.md
  - name: Discussions
    url: https://github.com/Katsute/Mal4J/discussions
    about: Check here before posting an issue
  - name: Official MyAnimeList API Club
    url: https://myanimelist.net/clubs.php?cid=13727
    about: We do not maintain the MyAnimeList API, issues regarding the API itself should be posted in their official club
