blank_issues_enabled: false
contact_links:
  - name: FAQ
    about: Check frequently asked questions before posting an issue
    url: https://github.com/Katsute/Mal4J/blob/main/faq.md
  - name: Discussions
    url: https://github.com/Katsute/Mal4J/discussions
    about: Check here before posting an issue
  - name: Official MyAnimeList API Club
    url: https://myanimelist.net/clubs.php?cid=13727
    about: We do not maintain the MyAnimeList API, issues regarding the API itself should be posted in their official club