name: Feature Request
description: Suggest a new feature
labels: [feature request]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Before opening a feature request please check that your idea was not already discussed in the following:

        * [Issues](https://github.com/KatsuteDev/Mal4J/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature+request%22)
        * [Discussions](https://github.com/KatsuteDev/Mal4J/discussions)

        Please also check that:

        * This feature makes sense for the project.
        * This feature does not already exist.
        * You are running the latest version.

        This library can only add features that are present in [MyAnimeList REST API](https://myanimelist.net/apiconfig/references/api/v2) or can be accomplished using existing features of the API.

  - type: textarea
    attributes:
      label: Feature
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reason
      description: |
        Explain why you think this feature should be added.
    validations:
      required: true