name: Java CI
on:
  push: {}
  pull_request:
    branches: [main]

jobs:
  build:
    name: Compile (Java ${{ matrix.java }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        java: [8, 9, 11, 17]
      fail-fast: false
    steps:
      - name: 📤 Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: ☕ Install Java
        uses: actions/setup-java@v2.3.0
        if: matrix.java != '9'
        with:
          architecture: x64
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven

      - name: ☕ Install Java 9
        uses: actions/setup-java@v2.3.0
        if: matrix.java == '9'
        with:
          architecture: x64
          distribution: adopt
          java-version: ${{ matrix.java }}
          cache: maven

      - name: ✔ Compile with Maven
        run: mvn compile -DskipTests --no-transfer-progress

  codeql:
    name: CodeQL (Java 17)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build
    if: github.event_name == 'pull_request' || github.actor != 'dependabot[bot]'
    steps:
      - name: 📤 Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: 📚 Install CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: java

      - name: ☕ Install Java
        uses: actions/setup-java@v2.3.0
        with:
          architecture: x64
          distribution: temurin
          java-version: 17
          cache: maven

      - name: ✔ Compile with Maven
        run: mvn compile -DskipTests --no-transfer-progress

      - name: ✔ Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  test:
    name: Test (Java ${{ matrix.java }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: codeql
    strategy:
      matrix:
        java: [8, 11, 17]
      fail-fast: false
    steps:
      - name: 📤 Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: ☕ Install Java
        uses: actions/setup-java@v2.3.0
        with:
          architecture: x64
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven

      - name: ✔ Test with Maven
        run: mvn test -fae --no-transfer-progress
