name: MyAnimeList CI
on: [workflow_dispatch]

permissions: read-all

concurrency: mal-test

jobs:
  mal_ci:
    name: MyAnimeList CI (Java ${{ matrix.java }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 17]
      fail-fast: false
      max-parallel: 1
    steps:
      - name: 📤 Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: ☕ Install Java
        uses: actions/setup-java@v2.3.0
        with:
          architecture: x64
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: 🔐 Load OAuth Token
        run: |
          echo ${{ secrets.MAL_OAUTH }} > src/test/java/resources/oauth.txt

      - name: ✔ Test with Maven
        run: mvn test -fae --no-transfer-progress