name: MyAnimeList CI
on: [workflow_dispatch]

permissions: read-all

concurrency:
  group: mal-test
  cancel-in-progress: true

jobs:
  mal_ci:
    name: MyAnimeList CI [${{ matrix.auth }}] (Java ${{ matrix.java }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        auth: ["Client", "Token"]
        java: [8, 11, 17, 21]
      fail-fast: false
      max-parallel: 1
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          architecture: x64
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Load Client ID
        if: matrix.auth == 'Client'
        run: |
          echo ${{ secrets.MAL_CLIENT }} > src/test/java/resources/client.txt

      - name: Load OAuth Token
        if: matrix.auth == 'Token'
        run: |
          echo ${{ secrets.MAL_TOKEN }} > src/test/java/resources/token.txt

      - name: Test with Maven
        continue-on-error: true
        run: mvn test -fae --no-transfer-progress

      - name: Checkout JUnit Report
        uses: actions/checkout@v4
        with:
          repository: Katsute/JUnit-Report
          ref: 862f2f943b2274619fe0ed4ef9d8bbe965607a1f
          path: ./.github/junit-report
          token: ${{ secrets.JUNIT_PAT }}

      - name: Generate Report
        uses: ./.github/junit-report