name: MyAnimeList CI
on: [workflow_dispatch]

permissions: read-all

concurrency:
  group: mal-test
  cancel-in-progress: true

jobs:
  mal_ci:
    name: MyAnimeList CI [${{ matrix.auth }}] (Java ${{ matrix.java }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        auth: ["Client", "Token"]
        java: [8, 11, 17, 21]
      fail-fast: false
      max-parallel: 1
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          architecture: x64
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Load Client ID
        if: matrix.auth == 'Client'
        run: |
          echo ${{ secrets.MAL_CLIENT }} > src/test/java/resources/client.txt

      - name: Load OAuth Token
        if: matrix.auth == 'Token'
        run: |
          echo ${{ secrets.MAL_TOKEN }} > src/test/java/resources/token.txt

      - name: Test with Maven
        continue-on-error: true
        run: mvn test -fae --no-transfer-progress

      - name: Check Token
        run: |-
          if [ "${{ secrets.KDEVBOT_PRIVATE_KEY }}" != '' ]
          then
            echo "authenticated=true" >> $GITHUB_ENV;
          fi

      - name: Authenticate
        id: auth
        if: ${{ env.authenticated }}
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.KDEVBOT_APP_ID }}
          private-key: ${{ secrets.KDEVBOT_PRIVATE_KEY }}
          owner: KatsuteDev

      - name: Checkout JUnit Report
        if: ${{ env.authenticated }}
        uses: actions/checkout@v4
        with:
          repository: KatsuteDev/junit-report
          ref: 154990716214c5d45d19ccfb810e8fd6c387d485
          path: ./.junit-report
          token: ${{ steps.auth.outputs.token }}

      - name: Generate Report
        if: ${{ env.authenticated }}
        uses: ./.junit-report
        with:
          job: MyAnimeList CI [${{ matrix.auth }}] (Java ${{ matrix.java }})
          token: ${{ steps.auth.outputs.token }}