name: MyAnimeList CI
on: [workflow_dispatch]

permissions: read-all

concurrency: mal-test

jobs:
  mal_ci:
    name: MyAnimeList CI [${{ matrix.auth }}] (Java ${{ matrix.java }})
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        auth: ["Client", "Token"]
        java: [8, 11, 17, 18]
      fail-fast: false
      max-parallel: 1
    steps:
      - name: 📤 Checkout Repository
        uses: actions/checkout@v3

      - name: ☕ Install Java
        uses: actions/setup-java@v3
        with:
          architecture: x64
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: 🔐 Load Client ID
        if: matrix.auth == 'Client'
        run: |
          echo ${{ secrets.MAL_CLIENT }} > src/test/java/resources/client.txt

      - name: 🔐 Load OAuth Token
        if: matrix.auth == 'Token'
        run: |
          echo ${{ secrets.MAL_TOKEN }} > src/test/java/resources/token.txt

      - name: ✔ Test with Maven
        continue-on-error: true
        run: mvn test -fae --no-transfer-progress

      - name: 📤 Checkout Action
        uses: actions/checkout@v3
        with:
          repository: Katsute/JUnit-Report
          ref: 6990e1dd88a9c3826b600690b0ada9b544470e8a
          path: ./.github/junit-report
          token: ${{ secrets.SINON }}

      - name: ✔ Generate Report
        uses: ./.github/junit-report
        with:
          path: .
